name: 'Publish Code Analysis'
description: 'Publish .NET Code Analysis as a PR Comment'
branding:
  icon: git-pull-request
  color: purple
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
    
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Run PowerShell Script
      shell: PowerShell
      run: pwsh -File verify-code-analysis.ps1