name: "Publish Code Analysis"
description: "Publish .NET Code Analysis as a PR Comment"
branding:
  icon: git-pull-request
  color: purple
inputs:
  search-directory:
    description: "Base directory to begin searching for SARIF files"
    required: true
  use-codeql:
    description: "Whether or not to upload the Sarif files with Code QL"
    required: true
runs:
  using: "composite"
  steps:
    - name: Run PowerShell Script
      shell: pwsh
      env:
        SARIF_BASE_DIR: ${{inputs.search-directory}}
      run: |
        # Print working directory for debugging
        Write-Host "Current directory: $(pwd)"

        # Run the PowerShell script
        $path =  Join-Path ${{GITHUB.ACTION_PATH}} "scripts/verify-code-analysis.ps1"

        & $path
    - name: Post Comment on PR using GitHub Script
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          const requestBodyPath = path.join(process.env.GITHUB_WORKSPACE, 'request-body.md');
          const body = fs.readFileSync(requestBodyPath, 'utf8');
          const issue_number = context.payload.pull_request.number;

          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issue_number,
            body: body // Use Markdown content directly
          });

    - name: Upload SARIF files
      uses: github/codeql-action/upload-sarif@v3
      if: ${{ inputs.use-codeql }}
      with:
        sarif_file: ${{ github.workspace }}/combined-code-analysis.sarif
